### ISSUE TITLE
AbevJava for  ÁNYK howto for @monolithon  (new thread)

### ISSUE THREAD

**Issue by porteusconf** [porteusconf/porteusconf.github.io#11]
This issue is to track separately and discuss ways to do abevjava_install.jar ...
At [https://github.com/chromebrew/chromebrew/issues/9945#issuecomment-2200731327](https://github.com/chromebrew/chromebrew/issues/9945#issuecomment-2200731327)  @monolithon said

> I tried, but doesnt work for me:
`java -jar abevjava_install.jar WAYLAND_DISPLAY=wayland-1`

https://nav.gov.hu/pfile/programFile?path=/nyomtatvanyok/letoltesek/nyomtatvanykitolto_programok/nyomtatvany_apeh/keretprogramok/AbevJava

Hello @monolithon 
Did this ever work using crew-installed oracle jdk? 

If never worked, a better but slower way to run on chromeos is in Linux (in vt on Chromebook, or dualboot).  Instructions for Linux are at [https://nav.gov.hu/nyomtatvanyok/letoltesek/nyomtatvanykitolto_programok/nyomtatvany_apeh/keretprogramok/javakitolto](https://nav.gov.hu/nyomtatvanyok/letoltesek/nyomtatvanykitolto_programok/nyomtatvany_apeh/keretprogramok/javakitolto)

Others use docker, like this one for macos, but docker would best be run in Linux on chromebook rather than with crew I think:
[https://github.com/H2CO3/abevjava-docker](https://github.com/H2CO3/abevjava-docker)

**Comment by backendoadmin** [comment]
Thank you for raising a separate issue for this.

Yes, it worked on Chromebrew without any extra workaround; I just had to switch to Java 8. based on this solution: https://superuser.com/questions/1394708/why-is-oracle-java8-installer-not-installing-on-ubuntu-18-04 

It also works on Chromebook Developer Linux, but I prefer Chromebrew.

Thank you.

**Comment by backendoadmin** [comment]
`chronos@localhost ~/Downloads/chromebrew $ java -jar abevjava_install.jar WAYLAND_DISPLAY=wayland-1
Version = jarinstaller v 1.0.20
(0) JarInstaller : file:/home/chronos/user/Downloads/chromebrew/abevjava_install.jar
Operációs rendszer = linux,unknown
Operációs rendszer = linux,unknown
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:131)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.Toolkit$2.run(Toolkit.java:860)
        at java.awt.Toolkit$2.run(Toolkit.java:855)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
        at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2041)
        at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1158)
        at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:431)
        at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
        at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)
        at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1349)
        at javax.swing.UIManager.initialize(UIManager.java:1459)
        at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
        at javax.swing.UIManager.getUI(UIManager.java:1006)
        at javax.swing.JPanel.updateUI(JPanel.java:126)
        at javax.swing.JPanel.<init>(JPanel.java:86)
        at javax.swing.JPanel.<init>(JPanel.java:109)
        at javax.swing.JPanel.<init>(JPanel.java:117)
        at javax.swing.JRootPane.createGlassPane(JRootPane.java:546)
        at javax.swing.JRootPane.<init>(JRootPane.java:366)
        at javax.swing.JApplet.createRootPane(JApplet.java:161)
        at javax.swing.JApplet.<init>(JApplet.java:149)
        at jarinstaller.JarInstallerGUI.<init>(JarInstallerGUI.java:19)
        at jarinstaller.MainLogic.doGui(MainLogic.java:101)
        at jarinstaller.MainLogic.exec(MainLogic.java:80)
        at jarinstaller.JarInstaller.exec(JarInstaller.java:58)
        at jarinstaller.JarInstaller.main(JarInstaller.java:40)`
